/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ostdemon
 */
public class AddEmp extends javax.swing.JFrame {

    /**
     * Creates new form AddEmp
     */
    public AddEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        years = new javax.swing.JComboBox<>();
        day = new javax.swing.JComboBox<>();
        month = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Department = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        name4 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jobtitle = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        main = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        date = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Login As:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(630, 30, 80, 18);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(710, 30, 80, 20);

        jLabel3.setText("Employees Details");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(310, 50, 140, 18);

        jLabel4.setText("Employees ID:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(100, 130, 110, 18);
        getContentPane().add(name);
        name.setBounds(210, 280, 140, 30);

        jLabel5.setText("-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 70, 750, 10);

        jLabel6.setText("Username:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(100, 170, 110, 18);

        jTextField2.setEditable(false);
        jTextField2.setEnabled(false);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 120, 140, 30);

        jLabel7.setText("Password:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(100, 210, 110, 18);
        getContentPane().add(password);
        password.setBounds(210, 200, 140, 30);

        jLabel8.setText("Gender:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 190, 100, 18);

        years.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012" }));
        getContentPane().add(years);
        years.setBounds(530, 150, 140, 30);

        day.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(day);
        day.setBounds(530, 120, 70, 30);

        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(month);
        month.setBounds(600, 120, 70, 30);

        jLabel10.setText("Date of birth:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(420, 130, 110, 18);

        Department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programer", "System Analysis", "Business Analysis", "Project Manager" }));
        getContentPane().add(Department);
        Department.setBounds(210, 240, 140, 30);

        jLabel9.setText("Name:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(100, 290, 110, 18);

        jLabel11.setText("DD/MM/YYYY");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(420, 160, 100, 18);

        male.setText("Male");
        getContentPane().add(male);
        male.setBounds(530, 190, 60, 23);

        female.setText("Female");
        getContentPane().add(female);
        female.setBounds(600, 190, 80, 23);

        jLabel12.setText("Position:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 250, 110, 18);
        getContentPane().add(username);
        username.setBounds(210, 160, 140, 30);

        jLabel13.setText("Surname:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(100, 330, 110, 18);
        getContentPane().add(surname);
        surname.setBounds(210, 320, 140, 30);

        jLabel14.setText("Email:");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 370, 110, 18);
        getContentPane().add(email);
        email.setBounds(210, 360, 140, 30);

        jLabel15.setText("Contract:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 230, 110, 18);
        getContentPane().add(tel);
        tel.setBounds(530, 220, 140, 30);

        jLabel16.setText("Basic Salary:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(420, 270, 110, 18);
        getContentPane().add(name4);
        name4.setBounds(530, 260, 140, 30);

        jLabel17.setText("Job Title:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(420, 310, 110, 18);
        getContentPane().add(jobtitle);
        jobtitle.setBounds(530, 300, 140, 30);

        add.setText("Add Record");
        getContentPane().add(add);
        add.setBounds(70, 440, 150, 60);

        exit.setText("Exit");
        getContentPane().add(exit);
        exit.setBounds(590, 440, 140, 60);

        clear.setText("Clear");
        getContentPane().add(clear);
        clear.setBounds(250, 440, 140, 60);

        main.setText("Main Menu");
        getContentPane().add(main);
        main.setBounds(420, 440, 140, 60);

        jMenu1.setText("File");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        date.setText("date");
        jMenuBar1.add(date);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Department;
    private javax.swing.JButton add;
    private javax.swing.JButton clear;
    private javax.swing.JMenu date;
    private javax.swing.JComboBox<String> day;
    private javax.swing.JTextField email;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jobtitle;
    private javax.swing.JButton main;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField name;
    private javax.swing.JTextField name4;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> years;
    // End of variables declaration//GEN-END:variables
}
