/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import connection.connect;
import java.awt.event.KeyEvent;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;


public class searchemp extends javax.swing.JFrame {

    private String gender;
    connection.connect connect = new connection.connect();
    Connection connects = connect.get_Connections();
    ResultSet res = null;
    PreparedStatement pre = null;
    
    public searchemp() {
        initComponents();
        Update();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        loginuser.setText(String.valueOf(connection.Emp.username).toString());
        
       
        
    }
    
    private void Update(){
        try {
            String sql = "SELECT * FROM mydb.emp_detail";
            pre=connects.prepareStatement(sql);
            res=pre.executeQuery();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        finally{
            try {
                res.close();
                pre.close();
            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        dateofB = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        userlevel = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        basesalary = new javax.swing.JTextField();
        jobtitle = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        surname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        genre = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        loginuser = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel14.setText("Email:");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(60, 230, 110, 18);
        jPanel1.add(email);
        email.setBounds(170, 220, 140, 30);

        dateofB.setFont(new java.awt.Font("Ubuntu", 0, 12)); // NOI18N
        jPanel1.add(dateofB);
        dateofB.setBounds(490, 30, 140, 30);

        jLabel10.setText("Date of birth:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(380, 40, 110, 18);

        jLabel7.setText("User Level:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 70, 110, 18);

        userlevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(userlevel);
        userlevel.setBounds(170, 60, 140, 30);

        jLabel8.setText("Gender:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(380, 80, 100, 18);
        jPanel1.add(tel);
        tel.setBounds(490, 110, 140, 30);

        jLabel15.setText("Contract:");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(380, 120, 110, 18);

        position.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Programer", "System Analysis", "Business Analysis", "Project Manager" }));
        jPanel1.add(position);
        position.setBounds(170, 100, 140, 30);

        jLabel12.setText("Position:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(60, 110, 110, 18);

        jLabel9.setText("Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 150, 110, 18);
        jPanel1.add(name);
        name.setBounds(170, 140, 140, 30);

        jLabel16.setText("Basic Salary:");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(380, 160, 110, 18);
        jPanel1.add(basesalary);
        basesalary.setBounds(490, 150, 140, 30);
        jPanel1.add(jobtitle);
        jobtitle.setBounds(490, 190, 140, 30);

        jLabel17.setText("Job Title:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(380, 200, 110, 18);
        jPanel1.add(surname);
        surname.setBounds(170, 180, 140, 30);

        jLabel13.setText("Surname:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(60, 190, 110, 18);

        jLabel6.setText("Username:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 30, 110, 18);

        username.setEditable(false);
        jPanel1.add(username);
        username.setBounds(170, 20, 140, 30);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(300, 270, 120, 50);

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(160, 270, 120, 50);
        jPanel1.add(genre);
        genre.setBounds(490, 70, 140, 30);

        jButton4.setText("exit to menu");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(450, 270, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 70, 720, 330);

        jLabel11.setText("search emp's username");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(190, 40, 190, 18);

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(380, 30, 110, 30);

        jLabel2.setText("Login As:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(620, 10, 70, 18);

        loginuser.setMaximumSize(new java.awt.Dimension(44, 14));
        loginuser.setMinimumSize(new java.awt.Dimension(44, 14));
        loginuser.setPreferredSize(new java.awt.Dimension(44, 14));
        getContentPane().add(loginuser);
        loginuser.setBounds(690, 10, 90, 20);

        jButton3.setText("search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(510, 30, 80, 30);

        jMenu1.setText("File");

        jMenuItem2.setText("Attach Image");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Reset");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
            
    }//GEN-LAST:event_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(p==0){
            try {
                
                String v1= basesalary.getText();
                String v2 = search.getText();
                String v3 = name.getText();
                String v4 = surname.getText();
                String v5 = email.getText();
                String v6 = tel.getText();
                String v7 = dateofB.getText();
                String v8 = genre.getText();
                String v9 = jobtitle.getText();
                String v10 = userlevel.getSelectedItem().toString();
                String v11 = position.getSelectedItem().toString();
                
                String sql = "update mydb.emp_detail set BaseSalary='"+v1+"',Fname='"+v3+"',Lname='"+v4+"',Email='"+v5+"',Tel='"+v6+"',DateOfBirth='"+v7+"',Gender='"+v8+"',Jobtitle='"+v9+"',userlevel='"+v10+"',Position='"+v11+"'  where username='"+v2+"'";
                pre=connects.prepareStatement(sql);

                pre.execute();
                
                JOptionPane.showMessageDialog(null, "Record Updated");
                
                
                
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            Date date = GregorianCalendar
                               .getInstance().getTime();
            DateFormat format = DateFormat.getDateInstance();
            String dateE = format.format(date);
            Date d= new Date();
            SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
            String timeSt = time.format(d);
                       
            String auditdate=dateE;
            String audittime=timeSt;
            String statusC= "Update Records";
            String eid=connection.Emp.username;
                       
            try {
                            
                String sqlogin="insert into mydb.audit (userlogin,date,time,status) values ('"+eid+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                       
                pre=connects.prepareStatement(sqlogin);
                pre.execute();
                            //this.dispose();
                           
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            finally {

                try{
                    res.close();
                    pre.close();

                }  
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,e);
                    }
                }                       
        }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        try {
            
                String sql = "SELECT * FROM mydb.emp_detail where username=? ";
                pre=connects.prepareStatement(sql);
                pre.setString(1, search.getText());
                res=pre.executeQuery();
                
                if(res.next()){
                    
                    String addusername = res.getString("username");
                    username.setText(addusername);
                
                    String adduserlevel = res.getString("userlevel");
                    userlevel.setSelectedItem(adduserlevel);
                
                    String addposition = res.getString("Position");
                    position.setSelectedItem(addposition);
                
                    String addname=res.getString("Fname");
                    name.setText(addname);
                
                    String addsur = res.getString("Lname");
                    surname.setText(addsur);
                
                    String adde = res.getString("Email");
                    email.setText(adde);
                
                    String adddate=res.getString("DateOfBirth");
                    dateofB.setText(adddate);
                
                    String addgen = res.getString("gender");
                    genre.setText(addgen);
                
                    String addcon = res.getString("Tel");
                    tel.setText(addcon);
                
                    String addbase = res.getString("BaseSalary");
                    basesalary.setText(addbase);
                
                    String addjob = res.getString("Jobtitle");
                    jobtitle.setText(addjob);
                }              
            } 
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try {
                    res.close();
                    pre.close();
                } catch (Exception e) {
                }
            }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete record?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
            
            try {
                
                Date date = GregorianCalendar
                               .getInstance().getTime();
            DateFormat format = DateFormat.getDateInstance();
            String dateE = format.format(date);
            Date d= new Date();
            SimpleDateFormat time = new SimpleDateFormat("HH:mm:ss");
            String timeSt = time.format(d);
                       
            String auditdate=dateE;
            String audittime=timeSt;
            String statusC= "Update Records";
            String eid=connection.Emp.username;
                       
            try {
                            
                String sqlogin="insert into mydb.audit (userlogin,date,time,status) values ('"+eid+"','"+auditdate+"','"+audittime+"','"+statusC+"')";
                       
                pre=connects.prepareStatement(sqlogin);
                pre.execute();
                            //this.dispose();
                           
            } catch (Exception e) {
                
            }
                
            } catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Record Updated"); 
            }
            
            String sqr = "delete from mydb.emp_detail where username=? ";
            try {
                
                pre=connects.prepareStatement(sqr);
                pre.setString(1, username.getText());
                pre.execute();
                JOptionPane.showMessageDialog(null,"Record Deleted");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e);
            }
            
            finally{
                try {
                    res.close();
                    pre.close();
                } catch (Exception e) {
                }
            }
            
            try {
                String sq = "delete from mydb.emp where username=? ";
                pre=connects.prepareStatement(sq);
                pre.setString(1, username.getText());
                pre.execute();
                JOptionPane.showMessageDialog(null,"Data is deleted");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        MainMenu main = new MainMenu();
        main.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchemp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchemp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basesalary;
    private javax.swing.JTextField dateofB;
    private javax.swing.JTextField email;
    private javax.swing.JTextField genre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jobtitle;
    private javax.swing.JLabel loginuser;
    private javax.swing.JTextField name;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField search;
    private javax.swing.JTextField surname;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<String> userlevel;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
