-- MySQL Script generated by MySQL Workbench
-- Fri Oct  5 15:11:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema employees_info
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema employees_info
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `employees_info` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `employees_info` ;

-- -----------------------------------------------------
-- Table `employees_info`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`Department` (
  `idDep` INT NOT NULL,
  `department` VARCHAR(45) NULL,
  PRIMARY KEY (`idDep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`empinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`empinfo` (
  `Eid` VARCHAR(6) NOT NULL,
  `idposition` VARCHAR(6) NULL,
  `Fname` VARCHAR(45) NULL DEFAULT NULL,
  `Lname` VARCHAR(45) NULL DEFAULT NULL,
  `Email` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(200) NULL DEFAULT NULL,
  `phone` VARCHAR(10) NULL,
  `dateofbirth` DATE NULL,
  `gender` VARCHAR(2) NULL COMMENT 'M=man\nF=Female\n',
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `idDep` INT NULL,
  PRIMARY KEY (`Eid`),
  CONSTRAINT `fk_empinfo_Department1`
    FOREIGN KEY (`idDep`)
    REFERENCES `employees_info`.`Department` (`idDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'test';


-- -----------------------------------------------------
-- Table `employees_info`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`position` (
  `idposition` VARCHAR(6) NOT NULL,
  `Position` VARCHAR(20) NULL,
  `baseSalary` DOUBLE NULL,
  `Eid` VARCHAR(6) NULL,
  PRIMARY KEY (`idposition`),
  CONSTRAINT `fk_position_empinfo1`
    FOREIGN KEY (`Eid`)
    REFERENCES `employees_info`.`empinfo` (`Eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`dayOff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`dayOff` (
  `iddayOff` INT NOT NULL,
  `dayoff` VARCHAR(45) NULL,
  PRIMARY KEY (`iddayOff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`dayOffDescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`dayOffDescription` (
  `dayOff` INT NULL,
  `date` DATE NULL,
  `Eid` VARCHAR(6) NULL,
  CONSTRAINT `fk_dayOffDescription_dayOff`
    FOREIGN KEY (`dayOff`)
    REFERENCES `employees_info`.`dayOff` (`iddayOff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dayOffDescription_empinfo1`
    FOREIGN KEY (`Eid`)
    REFERENCES `employees_info`.`empinfo` (`Eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`Benafits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`Benafits` (
  `idBenafits` INT NOT NULL,
  `Benafits` VARCHAR(45) NULL,
  PRIMARY KEY (`idBenafits`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`BenefitsDescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`BenefitsDescription` (
  `idBenefits` INT NOT NULL,
  `Eid` VARCHAR(45) NULL,
  CONSTRAINT `fk_BenefitsDescription_empinfo1`
    FOREIGN KEY (`Eid`)
    REFERENCES `employees_info`.`empinfo` (`Eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BenefitsDescription_Benafits1`
    FOREIGN KEY (`idBenefits`)
    REFERENCES `employees_info`.`Benafits` (`idBenafits`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `employees_info`.`Timework`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `employees_info`.`Timework` (
  `idTimework` INT NOT NULL,
  `Eid` VARCHAR(6) NULL,
  `timein` DATE NULL,
  `timeout` DATE NULL,
  PRIMARY KEY (`idTimework`),
  CONSTRAINT `fk_Timework_empinfo1`
    FOREIGN KEY (`Eid`)
    REFERENCES `employees_info`.`empinfo` (`Eid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
